- src/main/kotlin/kr/weit/odya/controller/TestController.kt
- src/main/kotlin/kr/weit/odya/controller/test/TestController.kt
- src/main/kotlin/kr/weit/odya/controller/test/response/TestRespones.kt
- 팀장님이 주신 과제 수행
- /test api 추가
- https://weit.atlassian.net/browse/ODYA-7
> ODYA-7 팀장님이 주신 과제 수행

- .gitignore
- build.gradle.kts
- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/overview.adoc
- src/docs/asciidoc/test.adoc
- src/main/kotlin/kr/weit/odya/controller/ExceptionHandler.kt
- src/main/kotlin/kr/weit/odya/controller/TestController.kt
- src/main/kotlin/kr/weit/odya/controller/test/response/TestRespones.kt
- src/main/kotlin/kr/weit/odya/service/dto/TestDtos.kt
- src/test/kotlin/kr/weit/odya/controller/test/TestControllerTest.kt
- src/test/kotlin/kr/weit/odya/support/TestFixtures.kt
- src/test/kotlin/kr/weit/odya/support/test/BaseTests.kt
- src/test/kotlin/kr/weit/odya/support/test/ControllerTestHelper.kt
- src/test/kotlin/kr/weit/odya/support/test/RestDocsHelper.kt
- src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
- src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
- src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
- src/test/resources/org/springframework/restdocs/templates/request-parts.snippet
- src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
- 개발 팀원들 간의 공유를 위한 API 문서화 작업
- Spring Rest Docs 연동
- TestController Reqeust, Response DTO 수정
- DCI 패턴 적용
- Rest Docs 문서화 코드 개선
- [ODYA-13](https://weit.atlassian.net/jira/software/c/projects/ODYA/boards/1?modal=detail&selectedIssue=ODYA-13)
- test 패키지 내에 있는 Helper 클래스가 Helper 클래스 / Util 클래스 중 어느 영역에 속하는지 궁금합니다! 
(Util은 애플리케이션 전체적으로 사용하는 느낌이 강하다고 생각해서 일단 Helper 클래스로 명명했습니다.)
> ODYA-13 Rest Docs 작업

- src/main/kotlin/kr/weit/odya/config/JpaAuditingConfiguration.kt
- src/main/kotlin/kr/weit/odya/domain/BaseTimeEntity.kt
- src/main/kotlin/kr/weit/odya/domain/placeReview/PlaceReview.kt
- src/main/kotlin/kr/weit/odya/domain/user/User.kt
- src/main/resources/db/migration/V2__Add_place_review.sql
- src/test/resources/sql/data-h2.sql
- src/test/resources/sql/schema-h2.sql
- place_review 스키마 작성
- place_review entity 추가
- BaseTimeEntity 추가
- [ODYA-19](https://weit.atlassian.net/browse/ODYA-19)
- 장소 리뷰 테이블
> ODYA-19 한 줄 리뷰 테이블 Entity 및 테스트 작성

- src/main/kotlin/kr/weit/odya/controller/AuthController.kt
- src/main/kotlin/kr/weit/odya/service/AuthenticationService.kt
- src/test/kotlin/kr/weit/odya/controller/AuthControllerTest.kt
- src/test/kotlin/kr/weit/odya/service/AuthenticationServiceTest.kt
- src/test/kotlin/kr/weit/odya/service/FollowServiceTest.kt
- src/test/kotlin/kr/weit/odya/service/UserServiceTest.kt
- 회원가입 버그 수정
- 회원가입 정보 검증 후 FIREBASE 유저 등록
- FIREBASE 유저 등록 로직을 Transaction 범위에 포함
- [ODYA-75](https://weit.atlassian.net/browse/ODYA-75)
- 😊
> ODYA-75 회원가입 로직 수정

- .github/workflows/issueTransition.yml
- 지라 티켓 자동화를 적용합니다
- 이슈 트랜지션을 적용했습니다
- [ODYA-82](https://weit.atlassian.net/browse/ODYA-82)
- 이제 PR을 올리면 지라티켓의 상태가 자동으로 **이슈 대기중** 상태로 넘어가고 PR이 머지되면 **완료** 상태로 넘어갑니다.
> ODYA-82 서버 이슈트랜지션 적용

- src/docs/asciidoc/auth.adoc
- src/docs/asciidoc/follow.adoc
- src/docs/asciidoc/overview.adoc
- src/docs/asciidoc/test.adoc
- src/docs/asciidoc/user.adoc
- src/main/kotlin/kr/weit/odya/client/ClientException.kt
- src/main/kotlin/kr/weit/odya/config/handler/CustomAuthenticationEntryPoint.kt
- src/main/kotlin/kr/weit/odya/controller/AuthController.kt
- src/main/kotlin/kr/weit/odya/controller/ExceptionHandler.kt
- src/main/kotlin/kr/weit/odya/security/FirebaseTokenHelper.kt
- src/main/kotlin/kr/weit/odya/security/InvalidTokenException.kt
- src/main/kotlin/kr/weit/odya/security/filter/FirebaseTokenFilter.kt
- src/main/kotlin/kr/weit/odya/service/AuthenticationService.kt
- src/main/kotlin/kr/weit/odya/service/OdyaException.kt
- src/main/kotlin/kr/weit/odya/service/dto/AuthDtos.kt
- src/main/kotlin/kr/weit/odya/service/dto/ErrorResponse.kt
- src/main/kotlin/kr/weit/odya/support/exception/ErrorCode.kt
- src/main/kotlin/kr/weit/odya/support/log/Logger.kt
- src/main/kotlin/kr/weit/odya/util/ResultUtils.kt
- src/test/kotlin/kr/weit/odya/controller/AuthControllerTest.kt
- src/test/kotlin/kr/weit/odya/controller/FollowControllerTest.kt
- src/test/kotlin/kr/weit/odya/controller/PlaceReviewControllerTest.kt
- src/test/kotlin/kr/weit/odya/controller/UserControllerTest.kt
- src/test/kotlin/kr/weit/odya/controller/test/TestControllerTest.kt
- src/test/kotlin/kr/weit/odya/service/AuthenticationServiceTest.kt
- src/test/kotlin/kr/weit/odya/support/AuthFixtures.kt
- src/test/kotlin/kr/weit/odya/support/filter/TestTokenFilter.kt
- 클라이언트 측 에러 분기 처리의 편의성을 위한 작업
- 에러 응답 시, 상황에 따른 에러 코드 추가
- [ODYA-66](https://weit.atlassian.net/browse/ODYA-66)
- 😊
> ODYA-66 API 에러 응답에 에러 코드 추가

- build.gradle.kts
- src/docs/asciidoc/placeSearchHistory.adoc
- src/main/kotlin/kr/weit/odya/controller/PlaceSearchHistoryController.kt
- src/main/kotlin/kr/weit/odya/domain/placeSearchHistory/PlaceSearchHistory.kt
- src/main/kotlin/kr/weit/odya/domain/placeSearchHistory/PlaceSearchHistoryRepository.kt
- src/main/kotlin/kr/weit/odya/domain/user/User.kt
- src/main/kotlin/kr/weit/odya/service/PlaceSearchHistoryService.kt
- src/main/kotlin/kr/weit/odya/service/dto/PlaceSearchHistoryDto.kt
- src/main/resources/application-open-search.yml
- src/main/resources/application.yml
- src/test/kotlin/kr/weit/odya/controller/PlaceSearchHistoryControllerTest.kt
- src/test/kotlin/kr/weit/odya/service/PlaceReviewServiceTest.kt
- src/test/kotlin/kr/weit/odya/service/PlaceSearchHistoryServiceTest.kt
- src/test/kotlin/kr/weit/odya/support/PlaceSearchHistoryFixtures.kt
- src/test/kotlin/kr/weit/odya/support/config/TestMockBeanConfig.kt
- src/test/kotlin/kr/weit/odya/support/test/BaseTests.kt
- 장소 검색 기록 저장 API
- opensearch를 이용하여 검색어 저장
- 전체 검색 순위 TOP 10 
- 연령대별 검색 순위 TOP 10 
- [ODYA-46](https://weit.atlassian.net/browse/ODYA-46)
-  순위는 상위 10개만 나옵니다 ^_^
> ODYA-46 장소 검색 기록 API

- src/docs/asciidoc/placeReview.adoc
- src/docs/asciidoc/placeSearchHistory.adoc
- src/docs/asciidoc/user.adoc
- src/main/kotlin/kr/weit/odya/controller/PlaceReviewController.kt
- src/main/kotlin/kr/weit/odya/domain/placeReview/PlaceReviewRepository.kt
- src/main/kotlin/kr/weit/odya/service/PlaceReviewService.kt
- src/main/kotlin/kr/weit/odya/service/dto/PlaceReviewDtos.kt
- src/test/kotlin/kr/weit/odya/controller/PlaceReviewControllerTest.kt
- src/test/kotlin/kr/weit/odya/domain/placeReview/PlaceReviewRepositoryTest.kt
- src/test/kotlin/kr/weit/odya/service/PlaceReviewServiceTest.kt
- src/test/kotlin/kr/weit/odya/support/PlaceReviewFixture.kt
한 줄 리뷰 여부 확인 API 및 정렬 기준 적용
- 한 줄 리뷰 존재 여부 확인 API (true = 존재 / false = 존재하지 않음)
- 최신순 정렬
- 별점 높은 순 정렬
- 별점 낮은 순 정렬
[ODYA-106](https://weit.atlassian.net/browse/ODYA-106)
:)
> ODYA-106 한 줄 리뷰 여부 확인 API/정렬 기준 적용

- src/docs/asciidoc/topic.adoc
- src/main/kotlin/kr/weit/odya/controller/TopicController.kt
- src/main/kotlin/kr/weit/odya/domain/topic/TopicRepository.kt
- src/main/kotlin/kr/weit/odya/service/TopicService.kt
- src/main/kotlin/kr/weit/odya/service/dto/TopicDtos.kt
- src/test/kotlin/kr/weit/odya/controller/TopicControllerTest.kt
- src/test/kotlin/kr/weit/odya/domain/topic/TopicRepositoryTest.kt
- src/test/kotlin/kr/weit/odya/service/TopicServiceTest.kt
- src/test/kotlin/kr/weit/odya/support/CommunityFixtures.kt
- src/test/kotlin/kr/weit/odya/support/TopicFixtures.kt
- 특정 장소에 작성된 커뮤니티 글에 자주 연결된 토픽을 알수 있어야 한다
- 특정 장소에 가장 비번하게 연결된 토픽 조회 API
- [ODYA-140](https://weit.atlassian.net/browse/ODYA-140)
- 빠르게 쓱싹 처리했습니다 ㅎㅎ
> ODYA-140 가장 비번하게 나온 토픽 조회 API

- src/main/kotlin/kr/weit/odya/domain/agreedTerms/AgreedTerms.kt
- src/main/kotlin/kr/weit/odya/domain/community/Community.kt
- src/main/kotlin/kr/weit/odya/domain/community/CommunityContentImage.kt
- src/main/kotlin/kr/weit/odya/domain/communitycomment/CommunityComment.kt
- src/main/kotlin/kr/weit/odya/domain/contentimage/ContentImage.kt
- src/main/kotlin/kr/weit/odya/domain/favoritePlace/FavoritePlace.kt
- src/main/kotlin/kr/weit/odya/domain/favoriteTopic/FavoriteTopic.kt
- src/main/kotlin/kr/weit/odya/domain/follow/Follow.kt
- src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelCompanion.kt
- src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournal.kt
- src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalContent.kt
- src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalContentImage.kt
- src/main/kotlin/kr/weit/odya/domain/user/Profile.kt
- src/main/kotlin/kr/weit/odya/domain/user/User.kt
- src/main/resources/db/migration/V22__add_indices.sql
- src/test/resources/sql/schema-h2.sql
- FK에 인덱스가 빠져 있는게 많았다
- 미흡한 인덱스들 추가
- [ODYA-148](https://weit.atlassian.net/browse/ODYA-148)
- 혹시 빠진 인덱스나 잘못 설정된거 있으면 말씀해주세요~!
- 그리고 요 작업 하면서 알았는데 인덱스 이름이 테이블안에서만 유일하면 되는줄 알고있었는데 DB 전역적으로 유일해야하네요 ㅋㅋㅋㅋ..
- 따라서 인덱스 명들을 **테이블명_컬럼명_index** 요렇게 이름을 지었습니다
> ODYA-148 미흡한 인덱스 추가

- src/docs/asciidoc/user.adoc
- src/main/kotlin/kr/weit/odya/controller/UserController.kt
- src/main/kotlin/kr/weit/odya/domain/user/UserRepository.kt
- src/main/kotlin/kr/weit/odya/service/UserService.kt
- src/main/kotlin/kr/weit/odya/service/dto/UsersDtos.kt
- src/test/kotlin/kr/weit/odya/controller/UserControllerTest.kt
- src/test/kotlin/kr/weit/odya/domain/user/UserRepositoryTest.kt
- src/test/kotlin/kr/weit/odya/service/UserServiceTest.kt
- src/test/kotlin/kr/weit/odya/support/ParamFixtures.kt
- src/test/kotlin/kr/weit/odya/support/UserFixtures.kt
- 사용자 연락처에 있는 전화번호로 유저를 검색할수 있는 기능이 필요하다
- 전화번호로 사용자 검색 API 추가
- [ODYA-155](https://weit.atlassian.net/browse/ODYA-155)
- 클라에서 제보해줘서 빠르게 쓱싹 했습니다 ㅎㅎ
> ODYA-155 전화번호로 유저 검색

- src/docs/asciidoc/placeReview.adoc
- src/main/kotlin/kr/weit/odya/controller/PlaceReviewController.kt
- src/main/kotlin/kr/weit/odya/domain/placeReview/PlaceReviewRepository.kt
- src/main/kotlin/kr/weit/odya/service/PlaceReviewService.kt
- src/main/kotlin/kr/weit/odya/service/dto/PlaceReviewDtos.kt
- src/test/kotlin/kr/weit/odya/controller/PlaceReviewControllerTest.kt
- src/test/kotlin/kr/weit/odya/domain/placeReview/PlaceReviewRepositoryTest.kt
- src/test/kotlin/kr/weit/odya/service/PlaceReviewServiceTest.kt
- src/test/kotlin/kr/weit/odya/support/PlaceReviewFixture.kt
한 줄 리뷰의 평점은 따로 내려야한다.
- 평균 별점 API 추가
[ODYA-158](https://weit.atlassian.net/browse/ODYA-158)
- :)
> ODYA-158 한 줄 리뷰 평균 평점 분리

- src/docs/asciidoc/travelJournal.adoc
- src/main/kotlin/kr/weit/odya/controller/TravelJournalController.kt
- src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepository.kt
- src/main/kotlin/kr/weit/odya/service/TravelJournalService.kt
- src/main/kotlin/kr/weit/odya/service/dto/TravelJournalDtos.kt
- src/test/kotlin/kr/weit/odya/controller/TravelJournalControllerTest.kt
- src/test/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepositoryTest.kt
- src/test/kotlin/kr/weit/odya/service/TravelJournalServiceTest.kt
- src/test/kotlin/kr/weit/odya/support/TravelJournalFixtures.kt
- 내가 태그된 여행일지를 조회하는 API가 필요하다
- 내가 태그된 여행일지 조회 API 추가
- 어색한 컨트롤러 메소드 명 수정
- [ODYA-165](https://weit.atlassian.net/browse/ODYA-165)
- 간단한 작업이라 빠르게 쓱싹 했습니다~! ㅋㅋㅋ
> ODYA-165 내가 태그된 여행일지 조회 API

- src/docs/asciidoc/community.adoc
- src/main/kotlin/kr/weit/odya/controller/CommunityController.kt
- src/main/kotlin/kr/weit/odya/domain/community/CommunityRepository.kt
- src/main/kotlin/kr/weit/odya/service/CommunityService.kt
- src/test/kotlin/kr/weit/odya/controller/CommunityControllerTest.kt
- src/test/kotlin/kr/weit/odya/domain/community/CommunityRepositoryTest.kt
- src/test/kotlin/kr/weit/odya/service/CommunityServiceTest.kt
토픽으로 커뮤니티 글 조회
- 토픽으로 커뮤니티 전체 목록 조회 API 추가
- [ODYA-175](https://weit.atlassian.net/browse/ODYA-175)
:)
> ODYA-175 토픽으로 커뮤니티 글 조회 API

- src/docs/asciidoc/community.adoc
- src/main/kotlin/kr/weit/odya/controller/CommunityController.kt
- src/main/kotlin/kr/weit/odya/domain/community/CommunityRepository.kt
- src/main/kotlin/kr/weit/odya/domain/communitycomment/CommunityCommentRepository.kt
- src/main/kotlin/kr/weit/odya/domain/communitylike/CommunityLike.kt
- src/main/kotlin/kr/weit/odya/domain/communitylike/CommunityLikeRepository.kt
- src/main/kotlin/kr/weit/odya/service/CommunityService.kt
- src/main/kotlin/kr/weit/odya/service/dto/CommunityCommentDtos.kt
- src/main/kotlin/kr/weit/odya/service/dto/CommunityDtos.kt
- src/main/resources/db/migration/V31__community_index_created_date.sql
- src/test/kotlin/kr/weit/odya/controller/CommunityControllerTest.kt
- src/test/kotlin/kr/weit/odya/domain/community/CommunityRepositoryTest.kt
- src/test/kotlin/kr/weit/odya/domain/communitycomment/CommunityCommentRepositoryTest.kt
- src/test/kotlin/kr/weit/odya/domain/communitylike/CommunityLikeRepositoryTest.kt
- src/test/kotlin/kr/weit/odya/service/CommunityServiceTest.kt
- src/test/kotlin/kr/weit/odya/support/CommunityCommentFixtures.kt
- src/test/kotlin/kr/weit/odya/support/CommunityFixtures.kt
- src/test/kotlin/kr/weit/odya/support/CommunityLikeFixtures.kt
- src/test/resources/sql/schema-h2.sql
댓글 단 커뮤니티 & 좋아요 누른 커뮤니티 조회 API 
- 댓글 단 커뮤니티 전체 목록 조회 API 추가
- 좋아요 누른 커뮤니티 전체 목록 조회 API 추가
- [ODYA-182](https://weit.atlassian.net/browse/ODYA-182)
:)
> ODYA-182 사용자가 단 댓글, 사용자가 좋아요 누른 게시글 조회 API

- src/main/kotlin/kr/weit/odya/service/CommunityService.kt
- src/main/kotlin/kr/weit/odya/service/dto/CommunityDtos.kt
- src/test/kotlin/kr/weit/odya/controller/CommunityControllerTest.kt
- src/test/kotlin/kr/weit/odya/service/CommunityServiceTest.kt
- src/test/kotlin/kr/weit/odya/support/CommunityFixtures.kt
- 커뮤니티 조회 시, 작성자와 생성일이 필요하다.
- 커뮤니티 조회 응답 값에 작성자와 생성일 추가
- [ODAY-184](https://weit.atlassian.net/browse/ODYA-184)
- 👍
> ODAY-184 커뮤니티 응답 값 수정

- src/docs/asciidoc/favoritePlace.adoc
- src/docs/asciidoc/follow.adoc
- src/docs/asciidoc/placeReview.adoc
- src/main/kotlin/kr/weit/odya/controller/FavoritePlaceController.kt
- src/main/kotlin/kr/weit/odya/controller/FollowController.kt
- src/main/kotlin/kr/weit/odya/controller/PlaceReviewController.kt
- src/main/kotlin/kr/weit/odya/service/FollowService.kt
- src/test/kotlin/kr/weit/odya/controller/FavoritePlaceControllerTest.kt
- src/test/kotlin/kr/weit/odya/controller/FollowControllerTest.kt
- src/test/kotlin/kr/weit/odya/controller/PlaceReviewControllerTest.kt
- src/test/kotlin/kr/weit/odya/service/FollowServiceTest.kt
- 원하지 않는 팔로워를 삭제할 수 있어야한다. 
- 문자열 공백 처리
- 팔로워 삭제 API
- @ NotNull -> @ NotBlank
- [ODYA-201](https://weit.atlassian.net/browse/ODYA-201)
- :)
> ODYA-201 팔로워 취소 API

- src/docs/asciidoc/report.adoc
- src/main/kotlin/kr/weit/odya/domain/report/ReportReason.kt
- 신고 사유에 저작권 위배가 없다.
- 저작권 위배(COPYRIGHT_VIOLATION) 추가
- [ODYA-206](https://weit.atlassian.net/browse/ODYA-206)
- 종민님 제보로 처리했습니다.
> ODYA-206 신고 사유 추가

- src/main/kotlin/kr/weit/odya/service/TravelJournalService.kt
- src/main/kotlin/kr/weit/odya/service/dto/TravelJournalDtos.kt
- src/test/kotlin/kr/weit/odya/controller/TravelJournalControllerTest.kt
- src/test/kotlin/kr/weit/odya/service/TravelJournalServiceTest.kt
- src/test/kotlin/kr/weit/odya/support/TravelJournalFixtures.kt
- 같이간 친구 항목에는 팔로잉 여부가 빠졌다
- 같이간 친구를 내릴때 팔로잉 여부 추가
- [ODYA-217](https://weit.atlassian.net/browse/ODYA-217)
- 희오님이 제보주셔서 빠르게 처리했습니다 ㅋㅋㅋ
> ODYA-217 같이간 친구에 팔로잉 여부 추가

- src/main/kotlin/kr/weit/odya/service/ObjectStorageService.kt
- 이미지가 내려갈때마다 URL이 달라져서 클라에서 이미지 캐싱을 못하고 있었다
- 인증기간(10분)이 지나기 전에는 같은 URL이 내려가도록 수정
- [ODYA-230](https://weit.atlassian.net/browse/ODYA-230)
- 예전부터 클라분들이 가끔 부탁하던 내용이기도하고 이번에 앱을 써보니까 사진을 가져올때 느린것 같아서 작업해봤습니다~! ㅋㅋㅋ
> ODYA-230 이미지 캐싱 추가

- src/docs/asciidoc/travelJournalBookmark.adoc
- src/main/kotlin/kr/weit/odya/controller/TravelJournalBookmarkController.kt
- src/main/kotlin/kr/weit/odya/domain/traveljournalbookmark/TravelJournalBookmarkRepository.kt
- src/main/kotlin/kr/weit/odya/service/TravelJournalBookmarkService.kt
- src/test/kotlin/kr/weit/odya/controller/TravelJournalBookmarkControllerTest.kt
- src/test/kotlin/kr/weit/odya/domain/traveljournalbookmark/TravelJournalBookmarkRepositoryTest.kt
- src/test/kotlin/kr/weit/odya/service/TravelJournalBookmarkServiceTest.kt
- 다른 사람의 여행일지 즐겨찾기를 조회할 수 있어야한다.
- 타인의 여행일지 즐겨찾기 조회 API
- [ODYA-232](https://weit.atlassian.net/browse/ODYA-232)
- :)
> ODYA-232 다른 사용자 여행일지 즐겨찾기 조회 API

- src/main/kotlin/kr/weit/odya/domain/traveljournalbookmark/TravelJournalBookmarkRepository.kt
- src/main/kotlin/kr/weit/odya/service/TravelJournalService.kt
- src/main/kotlin/kr/weit/odya/service/dto/TravelJournalDtos.kt
- src/test/kotlin/kr/weit/odya/controller/TravelJournalControllerTest.kt
- src/test/kotlin/kr/weit/odya/domain/traveljournalbookmark/TravelJournalBookmarkRepositoryTest.kt
- src/test/kotlin/kr/weit/odya/service/TravelJournalServiceTest.kt
- src/test/kotlin/kr/weit/odya/support/TravelJournalFixtures.kt
- 여행일지 목록 조회시 북마크 여부를 알 수 있어야한다.
- 여행일지 목록 조회 북마크 여부 응답값 추가
- [ODYA-238](https://weit.atlassian.net/browse/ODYA-238)
- 종민님이 제보해주셔서 처리했습니다 👍
> ODYA-238 여행일지 목록 조회 북마크 여부 추가
