build.gradle.kts, src/main/kotlin/kr/weit/odya/domain/user/Gender.kt, src/main/kotlin/kr/weit/odya/domain/user/SocialType.kt, src/main/kotlin/kr/weit/odya/domain/user/User.kt, src/main/kotlin/kr/weit/odya/domain/user/UserInformation.kt, src/main/resources/application-flyway.yml, src/main/resources/application.yml, src/main/resources/db/migration/V1__init.sql, src/test/kotlin/kr/weit/odya/support/converter/LocalDateAttributeConverter.kt, src/test/resources/sql/data-h2.sql, src/test/resources/sql/schema-h2.sql
- 데이터 베이스 형상 관리 및 DDL 업데이트를 위해 적용
- init.sql 초기 작성을 위해 user schema 작업
- flyway 적용 (sandbox 환경에만 적용)
- uesr entity 추가
- user soft delete 적용
- [ODYA-15](https://weit.atlassian.net/browse/ODYA-15)
- 초기 회원 테이블은 다음과 같습니다.
- 테스트 환경의 LocalDate <-> Timestmap Type Validate 오류는 @konempty 님이 구현하신 Converter를 적용했습니다.
- numeric <-> bigint Type Validate 오류는 @Id 어노테이션과 함께 Converter를 사용할 수 없어 `@Column(columnDefinition = "NUMERIC(19, 0)")` 코드를 추가해서 해결했습니다. 좀 더 나은 개선 방안이 있으면 코멘트 부탁드려요!
=> ODYA-15 flyway 작업

build.gradle.kts, src/main/kotlin/kr/weit/odya/OdyaApplication.kt, src/main/kotlin/kr/weit/odya/config/OpenSearchConfig.kt, src/main/kotlin/kr/weit/odya/config/properties/OpenSearchProperties.kt, src/main/resources/application-open-search.yml, src/main/resources/application.yml
- 추후 많은 데이터 검색에 사용될 ES(OpenSearch)연동을 했습니다
- 관련 라이브러리 추가
- 설정 추가
- [ODYA-29](https://weit.atlassian.net/browse/ODYA-29)
- 요거 ES 사용방법도 작업에 추가할까 하다가 어차피 임시코드일것 같아서 샌박에만 코드 넣어놨습니다
- 나중에 작업하실때 샌박에 사용코드 참고 부탁드립니다~!
=> ODYA-29 OpenSearch연동

Dockerfile, Dockerfile-cache, build.gradle.kts, src/main/kotlin/kr/weit/odya/config/properties/OpenSearchProperties.kt, src/main/resources/application-database.yml, src/main/resources/application-object-storage.yml, src/main/resources/application-open-search.yml, src/main/resources/application.yml, src/main/resources/bootstrap.yml
- 인프라 접속을 위한 비밀정보들을 공유하고 사용하기에 껄끄러웠다
- Spring cloud config를 이용한 자동 프로퍼티 주입을 추가 했다
- AWS의 Parameter store라는 기능을 사용했다
- 하지만 사람마다 다른 파일 위치는 그대로 환경변수를 통해 주입하도록 한다
- [ODYA-35](https://weit.atlassian.net/browse/ODYA-35)
- 대부분의 프로퍼티를 걷어 냈지만 AWS의 Parameter store를 접속하기 위한 프로퍼티가 2개 추가 되었고 
- 요 PR머지되면 그때 공유드리겠습니다~!
=> ODYA-35 Spring cloud config 도입

.github/workflows/issueTransition.yml
- 완료 상태가 잘못 정의가 되어있었다
- 제대로된 "완료"상태 적용
- https://github.com/weIT-1st/Odya-android/pull/22
- 이 PR도 제대로 안된다면 민성님을 혼내도록 하겠습니다
=> ODYA-82 완료 상태 이름 수정

src/main/kotlin/kr/weit/odya/service/dto/PlaceReviewDtos.kt
- 한줄리뷰 작성 DTO 수정
- @Notnull로 되어 있어 공백이나 빈 문자열에 대한 유효성 검사를 못함
- @Nonull -> @NotBlank로 변경
- [ODYA-116](https://weit.atlassian.net/browse/ODYA-116)
:)
=> ODYA-116 한줄리뷰 작성 DTO 수정

src/docs/asciidoc/follow.adoc, src/docs/asciidoc/user.adoc, src/main/kotlin/kr/weit/odya/controller/FollowController.kt, src/main/kotlin/kr/weit/odya/controller/UserController.kt, src/main/kotlin/kr/weit/odya/domain/agreedTerms/AgreedTermsRepository.kt, src/main/kotlin/kr/weit/odya/domain/follow/FollowRepository.kt, src/main/kotlin/kr/weit/odya/domain/user/UserRepository.kt, src/main/kotlin/kr/weit/odya/domain/user/UsersDocument.kt, src/main/kotlin/kr/weit/odya/domain/user/UsersDocumentRepository.kt, src/main/kotlin/kr/weit/odya/service/AuthenticationService.kt, src/main/kotlin/kr/weit/odya/service/FollowService.kt, src/main/kotlin/kr/weit/odya/service/UserService.kt, src/main/kotlin/kr/weit/odya/service/WithdrawService.kt, src/main/kotlin/kr/weit/odya/service/dto/PlaceReviewDtos.kt, src/main/kotlin/kr/weit/odya/service/dto/SliceDtos.kt, src/main/kotlin/kr/weit/odya/service/dto/UsersDtos.kt, src/main/resources/application-open-search.yml, src/test/kotlin/kr/weit/odya/controller/FollowControllerTest.kt, src/test/kotlin/kr/weit/odya/controller/UserControllerTest.kt, src/test/kotlin/kr/weit/odya/domain/follow/FollowRepositoryTest.kt, src/test/kotlin/kr/weit/odya/domain/user/UserRepositoryTest.kt, src/test/kotlin/kr/weit/odya/service/AuthenticationServiceTest.kt, src/test/kotlin/kr/weit/odya/service/FollowServiceTest.kt, src/test/kotlin/kr/weit/odya/service/UserServiceTest.kt, src/test/kotlin/kr/weit/odya/service/WithdrawServiceTest.kt, src/test/kotlin/kr/weit/odya/support/ParamFixtures.kt, src/test/kotlin/kr/weit/odya/support/UserFixtures.kt, src/test/kotlin/kr/weit/odya/support/config/TestMockBeanConfig.kt
- 사용자를 검색하는 기능이 필요하다
- 유저를 닉네임으로 검색하는 기능 추가
- 팔로잉 유저를 닉네임으로 검색하는 기능 추가
- 유저가 탈퇴할때 동의한 약관 이력을 삭제하지 않아 에러가 발생하고있던 버그도 같이 수정
- [ODYA-118](https://weit.atlassian.net/browse/ODYA-118)
- 개발보다 테스트 작성에 오래 걸린건 정말 오랜만이네요 ㅋㅋㅋㅋㅋ
- 도대체 두분은 지금까지 무슨 싸움을 하고계셨겁니까..! 고생이 진짜 많으셨겠네요 ㅋㅋ큐ㅠㅠ
=> ODYA-118 사용자 닉네임 검색 작업

src/docs/asciidoc/follow.adoc, src/main/kotlin/kr/weit/odya/controller/FollowController.kt, src/main/kotlin/kr/weit/odya/domain/follow/FollowRepository.kt, src/main/kotlin/kr/weit/odya/service/FollowService.kt, src/test/kotlin/kr/weit/odya/controller/FollowControllerTest.kt, src/test/kotlin/kr/weit/odya/domain/follow/FollowRepositoryTest.kt, src/test/kotlin/kr/weit/odya/service/FollowServiceTest.kt, src/test/kotlin/kr/weit/odya/support/UserFixtures.kt
- 알수도 있는 친구를 조회하는 API가 필요하다
- 알수도 있는 친구란 내가 팔로잉 하는 유저가 팔로잉하는 유저중에 내가 팔로잉 하지 않은 유저를 의미한다
- ex) 김한빈이 김채린을, 김채린이 최영찬을 요렇게 팔로우 하는 상황에서 최영찬은 김한빈의 알 수도 있는 친구가 된다
- 알 수도 있는 친구 조회 API 추가
- 이전에 반영되지 않은 리뷰사항 반영
- [ODYA-127](https://weit.atlassian.net/browse/ODYA-127)
- 어... 이게 만드는게 맞나 싶긴 할정도로 끔찍한 쿼리네요 ㅋㅋㅋ...
- 그리고 무거운 쿼리인 만큼 클라 분들이 자주 찌르지 않도록 가이드를 드릴 예정입니다.
=> ODYA-127 알수도 있는 친구 API 추가

src/test/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepositoryTest.kt
- 테스트가 깨진다
- 테스트가 실행되는 순서 차이로 깨지는데 일단 문제가 없도록 처리
- [ODYA-136](https://weit.atlassian.net/browse/ODYA-136)
- 순서 차이로 에러가 발생하는건 아마 id가 시퀀스로 증가하니까 그러는것 같은데
- 앞으로는 테스트 코드에서 id 비교 하는건 지양해야 할것 같네요 ㅋㅋㅋㅋ...
=> ODYA-136 깨지는 테스트 수정

src/main/kotlin/kr/weit/odya/service/dto/PlaceReviewDtos.kt, src/test/kotlin/kr/weit/odya/controller/PlaceReviewControllerTest.kt, src/test/kotlin/kr/weit/odya/service/PlaceReviewServiceTest.kt, src/test/kotlin/kr/weit/odya/support/PlaceReviewFixture.kt
- 한줄리뷰에 시간정보가 없었다
- 한줄리뷰 응답에 생성 시간 추가
- [ODYA-137](https://weit.atlassian.net/browse/ODYA-137)
- createdDate가 protected Setter라 테스트를 어떻게 처리할지 한참 고민했네요 ㅋㅋㅋㅋ
=> ODYA-137 한줄리뷰 시간 정보 추가

build.gradle.kts, src/docs/asciidoc/image.adoc, src/docs/asciidoc/index.adoc, src/main/kotlin/kr/weit/odya/controller/ImageController.kt, src/main/kotlin/kr/weit/odya/domain/contentimage/ContentImageRepository.kt, src/main/kotlin/kr/weit/odya/domain/follow/FollowRepository.kt, src/main/kotlin/kr/weit/odya/service/ImageService.kt, src/main/kotlin/kr/weit/odya/service/dto/ImageDtos.kt, src/main/kotlin/kr/weit/odya/support/validator/Latitude.kt, src/main/kotlin/kr/weit/odya/support/validator/Longitude.kt, src/test/kotlin/kr/weit/odya/controller/ImageControllerTest.kt, src/test/kotlin/kr/weit/odya/domain/contentImage/ContentImageRepositoryTest.kt, src/test/kotlin/kr/weit/odya/domain/follow/FollowRepositoryTest.kt, src/test/kotlin/kr/weit/odya/service/ImageServiceTest.kt, src/test/kotlin/kr/weit/odya/support/ContentImageFixtures.kt, src/test/kotlin/kr/weit/odya/support/SQLSupport.kt, src/test/resources/sql/schema-h2.sql
- 메인 화면에서는 사용자들이 작성한 커뮤니티와 여행일지에 태그된 장소들이 마커로 보여야 한다
- 커뮤니티와 여행일지에 장소가 태그되어있으면 추출해서 API 로 내려줌
- [ODYA-152](https://weit.atlassian.net/browse/ODYA-152)
- 예전에 mysql로 했을땐 이렇게 어렵진 않았던것 같은데 이상할 정도로 hiberante spatial 어렵네요 ㄷㄷ
=> ODYA-152 메인 뷰 좌표 조회 API

src/main/kotlin/kr/weit/odya/controller/CommunityController.kt, src/main/kotlin/kr/weit/odya/service/CommunityService.kt, src/main/kotlin/kr/weit/odya/service/dto/CommunityDtos.kt, src/main/kotlin/kr/weit/odya/service/dto/TravelJournalDtos.kt, src/test/kotlin/kr/weit/odya/controller/CommunityControllerTest.kt, src/test/kotlin/kr/weit/odya/service/CommunityServiceTest.kt, src/test/kotlin/kr/weit/odya/support/CommunityFixtures.kt, src/test/kotlin/kr/weit/odya/support/TravelJournalFixtures.kt
- 커뮤니티 목록 응답 값에 커뮤니티 내용, 유저 정보, 여행 일지 정보가 추가되어야 한다.
- 커뮤니티 목록 응답 값에 빠진 부분 추가
- [ODYA-177](https://weit.atlassian.net/browse/ODYA-177)
- 피그마를 보고 필요한 응답 값을 추가했는데 혹시라도 빠진 부분 있으면 코멘트 부탁드립니다!!!
=> ODYA-177 커뮤니티 목록 응답 값 수정

src/docs/asciidoc/overview.adoc, src/main/kotlin/kr/weit/odya/service/CommunityService.kt, src/main/kotlin/kr/weit/odya/service/dto/CommunityDtos.kt, src/test/kotlin/kr/weit/odya/controller/CommunityControllerTest.kt, src/test/kotlin/kr/weit/odya/service/CommunityServiceTest.kt, src/test/kotlin/kr/weit/odya/support/CommunityFixtures.kt
- 커뮤니티 목록조회할때 유저가 좋아요를 눌렀는지 확인할수 없다
- 413 statuscode에 대해 문서화가 안되어 있었다
- 커뮤니티 목록 조회 결과에 좋아요 여부 필드 추가
- 413에러 문서화
- [ODYA-193](https://weit.atlassian.net/browse/ODYA-193)
- 빠르게 쓱싹 했습니다 ㅋㅋㅋ
- 참고로 413에러는 저희 API 서버에서 내리는게 아니라 그 앞 인그레스가 내리는 응답이라 테스트 할수 없어서 테스트 코드는 없습니다 ㅎㅎ
=> ODYA-193 커뮤니티에 유저가 좋아요 눌렀는지 확인

src/main/kotlin/kr/weit/odya/controller/ExceptionHandler.kt, src/main/kotlin/kr/weit/odya/support/exception/ErrorCode.kt, src/main/resources/application.yml
- 이전에 요청 크기 제한을 해제 할때 파일사이즈 제한만 해제해서 request 전체 크기은 스프링 디폴트인 10MB로 남아 있었다
- 최대 request size 설정 추가
- [ODYA-203](https://weit.atlassian.net/browse/ODYA-203)
- 희오님의 제보로 설정이 빠졌다는걸 알아서 빠르게 쓱싹했습니다 ㅎㅎ..
=> ODYA-203 최대 요청 바디 크기 제한 수정

src/docs/asciidoc/community.adoc, src/docs/asciidoc/travelJournal.adoc, src/main/kotlin/kr/weit/odya/controller/CommunityController.kt, src/main/kotlin/kr/weit/odya/controller/TravelJournalController.kt, src/main/kotlin/kr/weit/odya/domain/community/CommunityRepository.kt, src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepository.kt, src/main/kotlin/kr/weit/odya/service/CommunityService.kt, src/main/kotlin/kr/weit/odya/service/TravelJournalService.kt, src/main/kotlin/kr/weit/odya/support/validator/NullOrNotBlank.kt, src/test/kotlin/kr/weit/odya/controller/CommunityControllerTest.kt, src/test/kotlin/kr/weit/odya/controller/TravelJournalControllerTest.kt, src/test/kotlin/kr/weit/odya/domain/community/CommunityRepositoryTest.kt, src/test/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepositoryTest.kt, src/test/kotlin/kr/weit/odya/service/CommunityServiceTest.kt, src/test/kotlin/kr/weit/odya/service/TravelJournalServiceTest.kt, src/test/kotlin/kr/weit/odya/support/ParamFixtures.kt, src/test/kotlin/kr/weit/odya/support/PlaceReviewFixture.kt
- 장소 id를 통해 커뮤니티와 여행일지를 검색해야하는 이슈가 니즈가 있다
- 커뮤니티 전체 검색 API 파라메터에 placeId 추가
- 내가쓴, 친구의, 추천 여행일지 API 파라메터에 placeId추가
- [ODYA-211](https://weit.atlassian.net/browse/ODYA-211)
- 오늘 아침 회의때 나온 이슈 빠르게 처리했습니다~!
=> ODYA-211 여행일지와 커뮤니티 placeId로 검색가능하게 수정

src/main/kotlin/kr/weit/odya/controller/FollowController.kt, src/main/kotlin/kr/weit/odya/controller/UserController.kt, src/main/kotlin/kr/weit/odya/service/FollowService.kt, src/main/kotlin/kr/weit/odya/service/dto/FollowDtos.kt, src/test/kotlin/kr/weit/odya/controller/FollowControllerTest.kt, src/test/kotlin/kr/weit/odya/controller/UserControllerTest.kt, src/test/kotlin/kr/weit/odya/service/FollowServiceTest.kt, src/test/kotlin/kr/weit/odya/support/FollowFixtures.kt
- 다른 사람의 팔로잉/팔로워 검색할때 내가 해당 유저를 팔로잉 하는지 확인하는 필드가 필요하다
- 전화번호로 유저 검색할때 10개 제한은 적다 늘려야 한다
- 팔로잉 API에 팔로잉 여부 추가
- 1회당 전화번호 검색 제한 30개로 상향
- [ODYA-221](https://weit.atlassian.net/browse/ODYA-221)
- IOS 개발자님들이 제보 해주셔서 빠르게 처리했습니다! ㅋㅋㅋ
=> ODYA-221 다른 사람 팔로워 조회시 내가 팔로잉 하는지 필드 추가

Dockerfile-cache, build.gradle.kts
- Spring boot 3.1.0~3.1.5의 DOS 취약점이 발견되었다
- 취약점이 해결된 3.1.6으로 업그레이드
- [ODYA-223](https://weit.atlassian.net/browse/ODYA-223)
- [CVE-2023-34055](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-34055)
- 저번주에 요거 회사에서 제가 패치했었는데 여기도 해두면 좋을것 같아서 작업해봤습니다~! ㅋㅋㅋ
=> ODYA-223 Spring 취약점 해결

src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepository.kt, src/test/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepositoryTest.kt
- 내가 태그된 여행일지 조회시 페이지네이션이 안되고 소팅도 안되고있었다
- 내가 태그된 여행일지 조회 쿼리에 slice쿼리 추가
- [ODYA-229](https://weit.atlassian.net/browse/ODYA-229)
- 요번 작업은 희오님이 제보해주셨고 서버 잘못이 아닌줄 알고 큰소리 쳤는데 서버 문제 맞았네요 ㅋㅋㅋ...
- 심지어 제가 예전에 잘못작업했던 부분입니다 ㅋ큐ㅠㅠ
=> ODYA-229 내가 태그된 여행일지 오류 수정

src/docs/asciidoc/travelJournal.adoc, src/main/kotlin/kr/weit/odya/controller/TravelJournalController.kt, src/main/kotlin/kr/weit/odya/domain/community/CommunityRepository.kt, src/main/kotlin/kr/weit/odya/service/TravelJournalService.kt, src/main/kotlin/kr/weit/odya/service/dto/TravelJournalDtos.kt, src/test/kotlin/kr/weit/odya/controller/TravelJournalControllerTest.kt, src/test/kotlin/kr/weit/odya/domain/community/CommunityRepositoryTest.kt, src/test/kotlin/kr/weit/odya/service/TravelJournalServiceTest.kt, src/test/kotlin/kr/weit/odya/support/TravelJournalFixtures.kt
- 여행일지는 visibility만 수정하는 플로우가 있다
- 여행일지의 공개 범위 수정 API 추가 
- [ODYA-228](https://weit.atlassian.net/browse/ODYA-228)
- 정아님이 제보해주셔서 빠르게 적용해봤습니다~!
=> ODYA-228 여행일지의 visibility 변경 API추가

src/main/kotlin/kr/weit/odya/domain/contentimage/ContentImageRepository.kt, src/main/kotlin/kr/weit/odya/service/UserService.kt, src/main/kotlin/kr/weit/odya/service/dto/UsersDtos.kt, src/test/kotlin/kr/weit/odya/controller/UserControllerTest.kt, src/test/kotlin/kr/weit/odya/service/UserServiceTest.kt, src/test/kotlin/kr/weit/odya/support/CommunityFixtures.kt, src/test/kotlin/kr/weit/odya/support/UserFixtures.kt
- 유저의 인생샷 개수로 클라가 알아야 한다
- 유저 통계 API 응답에 인생샷 개수 필드 추가
- [ODYA-237](https://weit.atlassian.net/browse/ODYA-237)
- 지혜님이 제보해주셔서 쓱삭 했습니다 ㅋㅋㅋ
=> ODYA-237 유저통계 API에 인생샷 개수 추가

src/docs/asciidoc/favoritePlace.adoc, src/main/kotlin/kr/weit/odya/controller/FavoritePlaceController.kt, src/test/kotlin/kr/weit/odya/controller/FavoritePlaceControllerTest.kt
- 타인의 관심 장소를 조회할 수 있어야한다.
- 타인의 관심 장소 조회 API 추가
- [ODYA-236](https://weit.atlassian.net/browse/ODYA-236)
- 희오님과 지혜님이 제보해주셔서 처리했습니다 👍
=> ODYA-236 타인의 관심장소 조회 API

src/docs/asciidoc/favoritePlace.adoc, src/main/kotlin/kr/weit/odya/controller/FavoritePlaceController.kt, src/test/kotlin/kr/weit/odya/controller/FavoritePlaceControllerTest.kt
- 타인의 관심 장소 수를 조회할 수 있어야한다.
- 타인의 관심 장소 수 조회 API 추가
- [ODYA-248](https://weit.atlassian.net/browse/ODYA-248)
- 지혜님이 제보해주셔서 처리했습니다 👍
=> ODYA-248 타인의 관심장소 수 조회
